### Task 1 - Set up the project

Installing the needed modules.

In [1]:
# !pip install openai==1.16.2 python-dotenv pyspark

Imporint the modules

In [1]:
from dotenv import load_dotenv
import os
from openai import OpenAI
import pandas as pd
import numpy as np

from pyspark.sql import SparkSession
from pyspark.sql.functions import concat_ws
from pyspark.sql import functions as F
from pyspark.sql.types import ArrayType, FloatType

from pyspark.ml.feature import VectorAssembler, PCA
from pyspark.ml.clustering import KMeans
import plotly.express as px

In [2]:
import sys

# Make sure Spark uses the same Python as your venv
os.environ["PYSPARK_PYTHON"] = sys.executable
os.environ["PYSPARK_DRIVER_PYTHON"] = sys.executable

spark = (SparkSession.builder
         .master("local[*]")
         .appName("ProductRecommenderSystem")
         .config("spark.driver.host", "127.0.0.1")
         .config("spark.driver.bindAddress", "127.0.0.1")
         .config("spark.ui.enabled", "false")
         .getOrCreate())

In [ ]:
# import os
# os.chdir(r'C:\Users\ashle\Project\Training\IBM\guided_project\ml_pyspark_recommendersystem')

Setup the OpenAI API

In [3]:
#Loading API jey
load_dotenv("apikey.env.txt")

client = OpenAI(api_key=os.getenv("APIKEY"))

Create a Spark session

In [4]:
spark = SparkSession.builder.appName("ProductRecommenderSyster").getOrCreate()
spark

Loading the dataset

In [5]:
file_path = 'products_dataset.csv'
df = spark.read.csv(file_path, header=True, inferSchema=True, samplingRatio=1)
df.show()

+----------+--------------------+--------------------+
|product_id|               title|         description|
+----------+--------------------+--------------------+
|        P0|Men's 3X Large Ca...|This heavyweight,...|
|        P1|Turmode 30 ft. RP...|If you need more ...|
|        P2|Large Tapestry Bo...|Polyester cover r...|
|        P3|16-Gauge-Sinks Ve...|It features a rec...|
|        P4|Men's Crazy Horse...|This 9 in. black ...|
|        P5|Mariana 6 ft. Mul...|With robust struc...|
|        P6|5 gal. #650C-2 Po...|BEHR PRO i300 Sem...|
|        P7|7/8 in. x 4-1/2 i...|DEWALT High Perfo...|
|        P8|  Ring Gold Bar Cart|This Ring Bar Car...|
|        P9|Traditional Silve...|This transitional...|
|       P10|15 in. x 59 in. O...|Its easy to add a...|
|       P11|1 qt. #350F-7 Wil...|BEHR PREMIUM PLUS...|
|       P12|Anthracite Cordle...|BlindsAvenue ligh...|
|       P13|SlimGrip 78-Inch ...|Luverne SlimGrip ...|
|       P14|6 in. x 28 in. x ...|Our Rustic Collec...|
|       P15|Espresso Cordless...|"The 2-1/2 in. Co...|
|       P16|5 gal. #BL-W10 Ma...|BEHR PREMIUM PLUS...|
|       P17|Eleyn 26 in. Indo...|This lighted chro...|
|       P18|1 qt. #M400-5 Bab...|BEHR PREMIUM PLUS...|
|       P19|10 in. x 4 in. x ...|Our faux wood bea...|
+----------+--------------------+--------------------+
only showing top 20 rows

### Task 2 - Prepare the dataset

Combine `title` and `description` Columns

In [6]:
df = df.withColumn('combined_text', concat_ws(" ", df.title,df.description))
df.show()

+----------+--------------------+--------------------+--------------------+
|product_id|               title|         description|       combined_text|
+----------+--------------------+--------------------+--------------------+
|        P0|Men's 3X Large Ca...|This heavyweight,...|Men's 3X Large Ca...|
|        P1|Turmode 30 ft. RP...|If you need more ...|Turmode 30 ft. RP...|
|        P2|Large Tapestry Bo...|Polyester cover r...|Large Tapestry Bo...|
|        P3|16-Gauge-Sinks Ve...|It features a rec...|16-Gauge-Sinks Ve...|
|        P4|Men's Crazy Horse...|This 9 in. black ...|Men's Crazy Horse...|
|        P5|Mariana 6 ft. Mul...|With robust struc...|Mariana 6 ft. Mul...|
|        P6|5 gal. #650C-2 Po...|BEHR PRO i300 Sem...|5 gal. #650C-2 Po...|
|        P7|7/8 in. x 4-1/2 i...|DEWALT High Perfo...|7/8 in. x 4-1/2 i...|
|        P8|  Ring Gold Bar Cart|This Ring Bar Car...|Ring Gold Bar Car...|
|        P9|Traditional Silve...|This transitional...|Traditional Silve...|
|       P10|15 in. x 59 in. O...|Its easy to add a...|15 in. x 59 in. O...|
|       P11|1 qt. #350F-7 Wil...|BEHR PREMIUM PLUS...|1 qt. #350F-7 Wil...|
|       P12|Anthracite Cordle...|BlindsAvenue ligh...|Anthracite Cordle...|
|       P13|SlimGrip 78-Inch ...|Luverne SlimGrip ...|SlimGrip 78-Inch ...|
|       P14|6 in. x 28 in. x ...|Our Rustic Collec...|6 in. x 28 in. x ...|
|       P15|Espresso Cordless...|"The 2-1/2 in. Co...|Espresso Cordless...|
|       P16|5 gal. #BL-W10 Ma...|BEHR PREMIUM PLUS...|5 gal. #BL-W10 Ma...|
|       P17|Eleyn 26 in. Indo...|This lighted chro...|Eleyn 26 in. Indo...|
|       P18|1 qt. #M400-5 Bab...|BEHR PREMIUM PLUS...|1 qt. #M400-5 Bab...|
|       P19|10 in. x 4 in. x ...|Our faux wood bea...|10 in. x 4 in. x ...|
+----------+--------------------+--------------------+--------------------+
only showing top 20 rows

get the combined_text column and convert it into a list

In [7]:
list_combined_text = df.select('combined_text').rdd.flatMap(lambda x: x).collect()
print(list_combined_text[:2])

["Men's 3X Large Carbon Heather Cotton/Polyester Rain Defender Paxton Heavyweight Hooded Zip-Front Sweatshirt This heavyweight, water-repellent hooded sweatshirt has a zip front for fast layering. ORIGINAL FIT. 13 oz., 75% cotton/25% polyester blend with Rain Defender durable water repellent. Attached, jersey-lined three-piece hood with drawcord closure. Antique-finish brass front zipper. Two front hand-warmer pockets have a hidden security pocket inside. Stretchable, spandex-reinforced rib-knit cuffs and waistband. Locker loop facilitates hanging.", "Turmode 30 ft. RP TNC Female to RP TNC Male Adapter Cable If you need more length between your existing wireless device and Hi-Gain Antenna, this is the product for you. It's compatible with most Wi-Fi Antennas, so it is easy for you to extend your wireless network. Just replace your existing cable that runs between your wireless device and Antenna and you're ready to use your network with extended range."]

Use OpenAI text embedding model to create the vector embeddings.

In [8]:
response = client.embeddings.create(
    input=list_combined_text,
    model="text-embedding-3-small",
    dimensions=512 # if the text is longer, can use higher dimensions
)

embedding_vectors = [data.embedding for data in response.data]
embedding_vectors[:2]  # show first 2 embedding vectors

[[0.042664770036935806,
  0.02092622220516205,
  -0.013632948510348797,
  -0.0020650296937674284,
  0.003196326084434986,
  -0.03726103901863098,
  0.027195259928703308,
  0.07833647727966309,
  0.0549556165933609,
  -0.06283164769411087,
  0.04421878606081009,
  0.048315733671188354,
  -0.0678468719124794,
  0.02521742321550846,
  0.022550875321030617,
  0.06392651796340942,
  0.10101096332073212,
  -0.030797747895121574,
  -0.08900266885757446,
  0.0706370398402214,
  -0.05802832543849945,
  0.06717582046985626,
  -0.034788742661476135,
  -0.07374507188796997,
  0.03450619429349899,
  0.04326518625020981,
  -0.05258927494287491,
  0.02505848929286003,
  0.05107057839632034,
  -0.01721777766942978,
  -0.003147762967273593,
  -0.022091733291745186,
  0.01910731941461563,
  -0.02458168938755989,
  0.04488983750343323,
  -0.06671668589115143,
  -0.02103217877447605,
  0.10447218269109726,
  -0.03870909661054611,
  0.025658903643488884,
  0.02348681539297104,
  -0.052801188081502914,
  0.018206696957349777,
  -0.06272569298744202,
  0.03268728777766228,
  0.03680189698934555,
  0.025976771488785744,
  0.02408722974359989,
  -0.033517275005578995,
  0.017906488850712776,
  -0.031769007444381714,
  -0.023204267024993896,
  -0.05573262274265289,
  0.052624594420194626,
  -0.036413393914699554,
  -0.02557060867547989,
  -0.04803318530321121,
  -0.04471324384212494,
  0.01654672622680664,
  -0.023398518562316895,
  -0.021191110834479332,
  -0.021456001326441765,
  -0.031892623752355576,
  -0.006145422346889973,
  -0.027530785650014877,
  -0.03341132029891014,
  0.01093108206987381,
  -0.017323734238743782,
  0.008065867237746716,
  -0.041887763887643814,
  0.06184272840619087,
  0.04128734767436981,
  0.031133275479078293,
  -0.029455645009875298,
  -0.08158577978610992,
  -0.0030881629791110754,
  0.0039358073845505714,
  -0.08278661221265793,
  0.011822874657809734,
  0.0357070229947567,
  -0.01721777766942978,
  0.07109618186950684,
  -0.02428148128092289,
  -0.018021274358034134,
  -0.057145364582538605,
  0.003158800071105361,
  -0.019654756411910057,
  0.012723496183753014,
  -0.0058098966255784035,
  -0.012246696278452873,
  0.0292613934725523,
  0.005050548352301121,
  0.019690074026584625,
  -0.02957925945520401,
  -0.04358305409550667,
  0.0018012444488704205,
  -0.0196370966732502,
  -0.037225719541311264,
  -0.03138050436973572,
  0.011920000426471233,
  -0.028078222647309303,
  -0.017977125942707062,
  -0.010136415250599384,
  0.01213191170245409,
  -0.05711004510521889,
  -0.008891437202692032,
  -0.10602619498968124,
  -0.005911437328904867,
  0.010374815203249454,
  -0.02089090459048748,
  -0.09966886043548584,
  0.07035449147224426,
  0.032528355717659,
  0.07067235559225082,
  -0.036907851696014404,
  -0.03556574881076813,
  0.031733687967061996,
  0.0032272296957671642,
  -0.004586992785334587,
  0.06544521450996399,
  0.021314727142453194,
  0.06219591200351715,
  -0.0124497776851058,
  -0.018242014572024345,
  0.0005168092902749777,
  -0.006794400047510862,
  -0.040439706295728683,
  -0.05265991389751434,
  0.0050858668982982635,
  -0.0008023926056921482,
  0.03715508058667183,
  0.024881897494196892,
  0.07607609033584595,
  -0.022868741303682327,
  -0.01721777766942978,
  0.01660853438079357,
  0.05241268128156662,
  0.009518341161310673,
  -0.03203389793634415,
  -0.1202242374420166,
  -0.03053285926580429,
  -0.04757404699921608,
  -0.02295703813433647,
  -0.003995407372713089,
  0.02414020709693432,
  0.020449422299861908,
  -0.013941985554993153,
  -0.0060924445278942585,
  -0.04997570440173149,
  0.08384616672992706,
  -0.055556029081344604,
  -0.06360865384340286,
  0.07840711623430252,
  0.028413748368620872,
  -0.0986093059182167,
  -0.011372563429176807,
  0.06473884731531143,
  0.04308859258890152,
  -0.055202845484018326,
  -0.03325238451361656,
  -0.066257543861866,
  0.003913733642548323,
  -0.00822480022907257,
  -0.00046879815636202693,
  0.1271466761827469,
  0.00014513703354168683,
  0.06993066519498825,
  -0.08426998555660248,
  -0.08540017902851105,
  -0.03565404564142227,
  0.0023707556538283825,
  -0.0446426086127758,
  0.002781333401799202,
  0.023027675226330757,
  0.021773867309093475,
  0.03666062280535698,
  -0.08264533430337906,
  0.019866667687892914,
  -0.03199857845902443,
  -0.12531010806560516,
  -0.009041541256010532,
  -0.045278340578079224,
  0.06357333809137344,
  -0.05068207532167435,
  -0.04414815083146095,
  -0.04354773461818695,
  0.031733687967061996,
  0.016396623104810715,
  0.017173629254102707,
  0.01101054809987545,
  0.0018133851699531078,
  0.028396088629961014,
  -0.025446992367506027,
  -0.003470044583082199,
  -0.034153006970882416,
  -0.08603591471910477,
  0.023186607286334038,
  0.07116681337356567,
  0.005659792572259903,
  0.08596527576446533,
  -0.05064675584435463,
  0.07868965715169907,
  0.03035626746714115,
  0.01910731941461563,
  -0.048774875700473785,
  0.00875016301870346,
  -0.009862696751952171,
  -0.007959911599755287,
  -0.06516266614198685,
  -0.029367348179221153,
  0.054602429270744324,
  0.004052800126373768,
  -0.041075438261032104,
  -0.003757007420063019,
  -0.009001807309687138,
  -0.002218444598838687,
  0.015699081122875214,
  -0.012476267293095589,
  0.020626015961170197,
  0.05294245854020119,
  -0.07024853676557541,
  0.03171603009104729,
  -0.06240782514214516,
  0.014515911228954792,
  -0.05145908147096634,
  0.06074785441160202,
  0.057957690209150314,
  0.04534897953271866,
  0.014418785460293293,
  -0.06297291815280914,
  0.03130986914038658,
  0.02440509758889675,
  -0.07819519937038422,
  0.01139905210584402,
  -0.06392651796340942,
  0.05771046131849289,
  0.0010667296592146158,
  -0.040580976754426956,
  -0.03355259448289871,
  -0.013968474231660366,
  -0.06929493695497513,
  -0.0021102814935147762,
  0.020767290145158768,
  0.06286696344614029,
  0.017191288992762566,
  0.01221137773245573,
  -0.02632995694875717,
  -0.04262945428490639,
  0.053754787892103195,
  -0.02604740858078003,
  0.03498299419879913,
  -0.030338607728481293,
  -0.04513706639409065,
  0.04496047645807266,
  0.02957925945520401,
  0.04962252080440521,
  0.012820622883737087,
  -0.0008211555541492999,
  -0.023257244378328323,
  -0.03168071061372757,
  -0.0668579563498497,
  0.0035384742077440023,
  -0.012802963145077229,
  0.0034104445949196815,
  -0.01807425171136856,
  0.051670994609594345,
  0.040404386818408966,
  -0.05831087380647659,
  0.024210844188928604,
  0.04407751187682152,
  -0.009933333843946457,
  0.061807408928871155,
  0.035300858318805695,
  0.09430044889450073,
  -0.04496047645807266,
  0.049940384924411774,
  -0.0028100297786295414,
  0.05580326169729233,
  0.020820267498493195,
  0.06989534944295883,
  -0.0688357949256897,
  -0.03676657751202583,
  0.0073859854601323605,
  0.015301748178899288,
  0.015760889276862144,
  0.046691082417964935,
  0.03916823863983154,
  0.06459756940603256,
  0.002708488842472434,
  0.0017692371038720012,
  0.017871171236038208,
  -0.023522133007645607,
  -0.01880711130797863,
  -0.017244266346096992,
  -0.048457007855176926,
  -0.028678636997938156,
  -0.09592510014772415,
  0.03715508058667183,
  -0.01624651812016964,
  -0.0648801177740097,
  0.019019022583961487,
  0.0702132135629654,
  -0.05548539385199547,
  0.044607289135456085,
  0.03920355811715126,
  0.08921457827091217,
  0.04496047645807266,
  -0.03277558460831642,
  -0.03261665254831314,
  -0.011796385049819946,
  0.005681866779923439,
  0.0372963547706604,
  -0.05364882946014404,
  -0.007955496199429035,
  -0.027707377448678017,
  -0.047008950263261795,
  0.02843140810728073,
  0.05463774874806404,
  -0.03810868039727211,
  -0.04806850478053093,
  0.0575338676571846,
  0.029649896547198296,
  -0.023504475131630898,
  -0.07946667075157166,
  0.0072005633264780045,
  -0.0339234359562397,
  -0.08434062451124191,
  -0.04308859258890152,
  -0.04015715792775154,
  -0.044925156980752945,
  -0.023221926763653755,
  0.004560503643006086,
  -0.0024502223823219538,
  -0.05195354297757149,
  0.018047763034701347,
  -0.004119022283703089,
  0.025129126384854317,
  -0.04852764680981636,
  0.024175526574254036,
  0.006326429545879364,
  -0.024864237755537033,
  -0.04142862185835838,
  -0.027053985744714737,
  -0.018736474215984344,
  0.0501876175403595,
  -0.05484966188669205,
  0.01898370496928692,
  0.02059069648385048,
  -0.004869540687650442,
  -0.0025429334491491318,
  0.016511408612132072,
  0.052801188081502914,
  -0.02011389657855034,
  -0.013977304100990295,
  0.020149216055870056,
  -0.025164445862174034,
  0.06074785441160202,
  -0.04937528818845749,
  0.05785173550248146,
  0.008052621968090534,
  0.02380468137562275,
  0.1118890717625618,
  -0.023398518562316895,
  -0.01878945156931877,
  0.0027283555828034878,
  0.057145364582538605,
  -0.038532502949237823,
  0.022603852674365044,
  -0.002966755535453558,
  -0.038673777133226395,
  0.03487703949213028,
  0.06343206018209457,
  0.030815407633781433,
  -0.015972800552845,
  -0.0497991107404232,
  0.026771437376737595,
  0.014771970920264721,
  0.07247360050678253,
  -0.02332788147032261,
  -0.02844906784594059,
  0.05251863971352577,
  0.049905069172382355,
  0.02860799990594387,
  0.09564255177974701,
  0.0841287150979042,
  0.002088207518681884,
  -0.02553528919816017,
  0.006149837281554937,
  0.06223123148083687,
  -0.027389511466026306,
  0.047008950263261795,
  -0.07310933619737625,
  -0.0011875851778313518,
  -0.04301795735955238,
  -0.015955140814185143,
  -0.010065778158605099,
  0.04337114095687866,
  0.03757890313863754,
  0.01757979206740856,
  0.07494589686393738,
  -0.010277689434587955,
  0.05107057839632034,
  -0.05831087380647659,
  0.049940384924411774,
  0.023910637944936752,
  -0.0036113185342401266,
  -0.0194428451359272,
  0.07116681337356567,
  -0.05499093607068062,
  -0.05110589787364006,
  -0.03298749774694443,
  0.02761908248066902,
  0.006154251750558615,
  0.04817445948719978,
  0.022533215582370758,
  0.1180344894528389,
  0.042523495852947235,
  -0.0019038888858631253,
  -0.0553441196680069,
  0.07381570339202881,
  -0.05223609134554863,
  -0.034470874816179276,
  -0.014524741098284721,
  -0.04453665390610695,
  -0.016573214903473854,
  0.057145364582538605,
  0.04358305409550667,
  -0.10362453758716583,
  -0.09691401571035385,
  0.004856296349316835,
  -0.010233541019260883,
  -0.026435911655426025,
  0.10298880189657211,
  0.028678636997938156,
  -0.08363424986600876,
  -0.005227140616625547,
  -0.0611010380089283,
  -0.006626637186855078,
  -0.00723588140681386,
  0.0440421923995018,
  -0.0030616740696132183,
  0.05244800075888634,
  0.0036885777954012156,
  -0.02313362993299961,
  0.001056796289049089,
  -0.006617807317525148,
  0.05979425460100174,
  0.014171555638313293,
  -0.064668208360672,
  -0.05597985163331032,
  0.015363556332886219,
  0.0255882665514946,
  -0.0745927095413208,
  0.025782519951462746,
  -0.023257244378328323,
  0.06802346557378769,
  -0.005103526171296835,
  0.04580811783671379,
  -0.0009740185341797769,
  -0.004163170233368874,
  0.04167585447430611,
  -0.0700366273522377,
  0.0700366273522377,
  -0.033517275005578995,
  -0.07014258205890656,
  0.009668444283306599,
  0.03293452039361,
  -0.004353007301688194,
  0.09952758997678757,
  -0.05047016218304634,
  -0.015531319193542004,
  -0.05658026784658432,
  0.012290844693779945,
  0.022550875321030617,
  0.0418524444103241,
  0.02523508109152317,
  -0.011752237565815449,
  -0.00856915581971407,
  -0.0507880300283432,
  -0.05661558732390404,
  0.005933511070907116,
  -0.01583152636885643,
  -0.05047016218304634,
  -0.03517724573612213,
  -0.007553748320788145,
  0.03429428115487099,
  -0.031415823847055435,
  0.07607609033584595,
  -0.04948124662041664,
  -0.041534580290317535,
  0.02172088995575905,
  -0.024634666740894318,
  -0.007606726139783859,
  -0.017729897052049637,
  0.002366340719163418,
  -0.03779081627726555,
  -0.03588361665606499,
  -0.03990992531180382,
  0.11245416849851608,
  -0.024722963571548462,
  0.03644871339201927,
  0.030267970636487007,
  0.01912497729063034,
  -0.09062732011079788,
  0.032846223562955856,
  0.044254105538129807,
  0.07268550992012024,
  0.018701156601309776,
  0.006622222252190113,
  0.025323377922177315,
  0.009624296799302101,
  0.04036906734108925],
 [0.04413316026329994,
  0.009090634062886238,
  0.02689831331372261,
  -0.013997085392475128,
  -0.0937788113951683,
  -0.03835500404238701,
  0.006101932376623154,
  0.011498198844492435,
  0.04416636750102043,
  0.06887296587228775,
  -0.010053659789264202,
  0.04413316026329994,
  -0.01120763085782528,
  -0.007314016576856375,
  0.04336937889456749,
  -0.08467987924814224,
  -0.019957885146141052,
  -0.03231118246912956,
  -0.07697566598653793,
  0.12951040267944336,
  0.004275503568351269,
  0.08056210726499557,
  -0.02228243090212345,
  -0.026699066162109375,
  -0.01947637088596821,
  0.04878225177526474,
  0.01569068245589733,
  0.06757786124944687,
  0.03795650973916054,
  -0.03656178340315819,
  -0.031314950436353683,
  -0.06299518793821335,
  -0.03510063886642456,
  -0.0374583937227726,
  -0.02575264498591423,
  -0.016595594584941864,
  -0.009978942573070526,
  -0.008355910889804363,
  0.03891953453421593,
  -0.042240314185619354,
  0.023262059316039085,
  0.021086949855089188,
  -0.021800916641950607,
  -0.0005660891183651984,
  0.01162272784858942,
  0.005375511944293976,
  0.012585754506289959,
  0.042107485234737396,
  0.035366300493478775,
  -0.00828949548304081,
  -0.00012524267367552966,
  0.04795205593109131,
  -0.07219374179840088,
  0.043967120349407196,
  -0.08567611128091812,
  0.10732759535312653,
  -0.021784313023090363,
  -0.023511119186878204,
  -0.006147592794150114,
  -0.02346130646765232,
  -0.08023003488779068,
  -0.04878225177526474,
  0.03169684112071991,
  -0.055855508893728256,
  0.021834125742316246,
  -6.326993025140837e-05,
  -0.01922731287777424,
  -0.008966104127466679,
  -0.0857425257563591,
  0.002698133233934641,
  0.03182967007160187,
  -0.045428261160850525,
  -0.04021463915705681,
  -0.01267707534134388,
  0.005641174037009478,
  -0.020970722660422325,
  -0.05847892537713051,
  0.030468150973320007,
  0.03456931561231613,
  0.029206255450844765,
  -0.02410885877907276,
  0.008438930846750736,
  -0.08122626692056656,
  0.007895153015851974,
  0.0038998404052108526,
  -0.004424938466399908,
  -0.06558539718389511,
  -0.06558539718389511,
  -0.03420402854681015,
  0.03182967007160187,
  0.056353628635406494,
  -0.05236869305372238,
  0.08939538151025772,
  -0.043502211570739746,
  -0.036262910813093185,
  -0.06558539718389511,
  -0.047254692763090134,
  -0.01844692975282669,
  0.04144332930445671,
  0.04469769075512886,
  0.04778601601719856,
  0.017649943009018898,
  -0.018895234912633896,
  -0.02116996981203556,
  0.008218929171562195,
  -0.04682299122214317,
  -0.018330702558159828,
  -0.041277289390563965,
  -0.02420848235487938,
  0.06628275662660599,
  -0.025437170639634132,
  -0.03606366366147995,
  0.008384968154132366,
  -0.06296198070049286,
  -0.01262726355344057,
  -0.019177502021193504,
  0.08321873098611832,
  0.014279351569712162,
  0.05250152200460434,
  0.009372900240123272,
  -0.05429474264383316,
  0.044398821890354156,
  0.025420567020773888,
  -0.12858058512210846,
  0.01618880033493042,
  -0.020671851933002472,
  -0.05987365171313286,
  0.00723514799028635,
  0.035831209272146225,
  0.04685619845986366,
  0.04708865284919739,
  0.008430629037320614,
  0.022000163793563843,
  -0.0003198844497092068,
  -0.04413316026329994,
  0.0028994556050747633,
  -0.012726887129247189,
  -0.024806221947073936,
  0.027064353227615356,
  -0.025437170639634132,
  0.0424063540995121,
  -0.04326975718140602,
  0.021468838676810265,
  -0.04592638090252876,
  -0.017135221511125565,
  0.038089338690042496,
  -0.06711295247077942,
  0.0028309645131230354,
  -0.05977402999997139,
  -0.006214008666574955,
  -0.12645527720451355,
  -0.04393391311168671,
  -0.05964119732379913,
  -0.029986638575792313,
  0.009837809018790722,
  -0.04682299122214317,
  -0.00818572100251913,
  0.03119872324168682,
  -0.022465072572231293,
  -0.03179646283388138,
  -0.04469769075512886,
  -0.004157200921326876,
  -0.09331390261650085,
  0.03722593933343887,
  -0.016172196716070175,
  0.006072875577956438,
  0.04851658642292023,
  -0.015342000871896744,
  -0.09670110046863556,
  0.002469829749315977,
  -0.026200950145721436,
  -0.04712186008691788,
  -0.0730571448802948,
  0.042572394013404846,
  0.0628291442990303,
  0.0032937980722635984,
  0.007920059375464916,
  -0.0618993304669857,
  0.03470214456319809,
  0.021302800625562668,
  -0.044000327587127686,
  -0.031962502747774124,
  0.05522456392645836,
  -0.03563196212053299,
  -0.025486981496214867,
  -0.02671566978096962,
  0.033788930624723434,
  0.0656186044216156,
  -0.016861258074641228,
  -0.023295268416404724,
  0.04197465255856514,
  0.06751144677400589,
  -0.031182119622826576,
  -0.0049977730959653854,
  -0.025553397834300995,
  -0.0011539708357304335,
  0.012286883778870106,
  -0.031929295510053635,
  0.008733649738132954,
  -0.013058965094387531,
  0.06707974523305893,
  -0.04094520956277847,
  0.012270280160009861,
  0.024988865479826927,
  -0.09152068197727203,
  -0.02488924190402031,
  -0.014960111118853092,
  0.02052241750061512,
  0.004993622191250324,
  -0.026117930188775063,
  0.07890172302722931,
  0.02904021553695202,
  0.003962105140089989,
  -0.011506500653922558,
  -0.005823817104101181,
  0.002901531057432294,
  -0.05718382075428963,
  0.01690276712179184,
  0.0022103937808424234,
  0.004283805377781391,
  -0.012560848146677017,
  0.01083404291421175,
  0.01148159522563219,
  0.015366907231509686,
  -0.01962580718100071,
  0.02048920840024948,
  -0.00222077127546072,
  -0.025304339826107025,
  0.05535739287734032,
  0.011249140836298466,
  -0.0024905845057219267,
  0.07318998128175735,
  -0.0162552148103714,
  -0.06329405307769775,
  -0.03709310665726662,
  0.023627346381545067,
  0.036196496337652206,
  -0.030600981786847115,
  -0.02668246254324913,
  -0.019575994461774826,
  -0.003700593486428261,
  0.0001905556709971279,
  0.06947070360183716,
  0.09371239691972733,
  -0.033938366919755936,
  -0.057250238955020905,
  -0.027695300057530403,
  -0.02729680761694908,
  0.017749566584825516,
  -0.05661929026246071,
  0.021834125742316246,
  0.05346455052495003,
  0.0801636129617691,
  -0.01854655332863331,
  0.06820880621671677,
  0.0941108912229538,
  -0.10135018825531006,
  0.00036113476380705833,
  -0.0034017234575003386,
  -0.04695582017302513,
  0.013249910436570644,
  -0.02689831331372261,
  0.017915604636073112,
  0.04160936549305916,
  0.03689385950565338,
  0.0013905763626098633,
  0.05114000290632248,
  0.00628457497805357,
  0.03051796369254589,
  0.014154822565615177,
  0.06628275662660599,
  -0.0187291968613863,
  0.0037234239280223846,
  0.015308793634176254,
  -0.07006844878196716,
  0.11250800639390945,
  0.08096060156822205,
  -0.008808367885649204,
  0.04436561465263367,
  -0.04742072895169258,
  -0.03232778608798981,
  -0.06618313491344452,
  -0.006064573302865028,
  0.01232009194791317,
  -0.041310496628284454,
  -0.0618993304669857,
  0.034834977239370346,
  0.08680517226457596,
  0.009821205399930477,
  -0.0848127081990242,
  0.03798971697688103,
  0.04280484840273857,
  -0.05884421244263649,
  0.0280107744038105,
  0.03705989941954613,
  -0.006180800963193178,
  0.0039579542353749275,
  0.0677771121263504,
  0.006504576653242111,
  -0.07637792825698853,
  -0.04609241709113121,
  0.08507836610078812,
  0.061368003487586975,
  -0.014860488474369049,
  0.009298182092607021,
  0.012793302536010742,
  0.019360143691301346,
  -0.02782813087105751,
  -0.014129916206002235,
  -0.019858261570334435,
  0.033722516149282455,
  0.01711861789226532,
  -0.013748026452958584,
  -0.038089338690042496,
  0.026798689737915993,
  0.022000163793563843,
  -0.007002693600952625,
  -0.023942820727825165,
  -0.01987486518919468,
  -0.029538333415985107,
  -0.06256348639726639,

Let't put the embedding vectors into our original dataframe

Convert embedding vectors list into a Pyspark DataFrame

In [9]:
features_column_names = [f"embedding_{i}" for i in range(len(embedding_vectors[0]))]
features_column_names

['embedding_0',
 'embedding_1',
 'embedding_2',
 'embedding_3',
 'embedding_4',
 'embedding_5',
 'embedding_6',
 'embedding_7',
 'embedding_8',
 'embedding_9',
 'embedding_10',
 'embedding_11',
 'embedding_12',
 'embedding_13',
 'embedding_14',
 'embedding_15',
 'embedding_16',
 'embedding_17',
 'embedding_18',
 'embedding_19',
 'embedding_20',
 'embedding_21',
 'embedding_22',
 'embedding_23',
 'embedding_24',
 'embedding_25',
 'embedding_26',
 'embedding_27',
 'embedding_28',
 'embedding_29',
 'embedding_30',
 'embedding_31',
 'embedding_32',
 'embedding_33',
 'embedding_34',
 'embedding_35',
 'embedding_36',
 'embedding_37',
 'embedding_38',
 'embedding_39',
 'embedding_40',
 'embedding_41',
 'embedding_42',
 'embedding_43',
 'embedding_44',
 'embedding_45',
 'embedding_46',
 'embedding_47',
 'embedding_48',
 'embedding_49',
 'embedding_50',
 'embedding_51',
 'embedding_52',
 'embedding_53',
 'embedding_54',
 'embedding_55',
 'embedding_56',
 'embedding_57',
 'embedding_58',
 'embedding_59',
 'embedding_60',
 'embedding_61',
 'embedding_62',
 'embedding_63',
 'embedding_64',
 'embedding_65',
 'embedding_66',
 'embedding_67',
 'embedding_68',
 'embedding_69',
 'embedding_70',
 'embedding_71',
 'embedding_72',
 'embedding_73',
 'embedding_74',
 'embedding_75',
 'embedding_76',
 'embedding_77',
 'embedding_78',
 'embedding_79',
 'embedding_80',
 'embedding_81',
 'embedding_82',
 'embedding_83',
 'embedding_84',
 'embedding_85',
 'embedding_86',
 'embedding_87',
 'embedding_88',
 'embedding_89',
 'embedding_90',
 'embedding_91',
 'embedding_92',
 'embedding_93',
 'embedding_94',
 'embedding_95',
 'embedding_96',
 'embedding_97',
 'embedding_98',
 'embedding_99',
 'embedding_100',
 'embedding_101',
 'embedding_102',
 'embedding_103',
 'embedding_104',
 'embedding_105',
 'embedding_106',
 'embedding_107',
 'embedding_108',
 'embedding_109',
 'embedding_110',
 'embedding_111',
 'embedding_112',
 'embedding_113',
 'embedding_114',
 'embedding_115',
 'embedding_116',
 'embedding_117',
 'embedding_118',
 'embedding_119',
 'embedding_120',
 'embedding_121',
 'embedding_122',
 'embedding_123',
 'embedding_124',
 'embedding_125',
 'embedding_126',
 'embedding_127',
 'embedding_128',
 'embedding_129',
 'embedding_130',
 'embedding_131',
 'embedding_132',
 'embedding_133',
 'embedding_134',
 'embedding_135',
 'embedding_136',
 'embedding_137',
 'embedding_138',
 'embedding_139',
 'embedding_140',
 'embedding_141',
 'embedding_142',
 'embedding_143',
 'embedding_144',
 'embedding_145',
 'embedding_146',
 'embedding_147',
 'embedding_148',
 'embedding_149',
 'embedding_150',
 'embedding_151',
 'embedding_152',
 'embedding_153',
 'embedding_154',
 'embedding_155',
 'embedding_156',
 'embedding_157',
 'embedding_158',
 'embedding_159',
 'embedding_160',
 'embedding_161',
 'embedding_162',
 'embedding_163',
 'embedding_164',
 'embedding_165',
 'embedding_166',
 'embedding_167',
 'embedding_168',
 'embedding_169',
 'embedding_170',
 'embedding_171',
 'embedding_172',
 'embedding_173',
 'embedding_174',
 'embedding_175',
 'embedding_176',
 'embedding_177',
 'embedding_178',
 'embedding_179',
 'embedding_180',
 'embedding_181',
 'embedding_182',
 'embedding_183',
 'embedding_184',
 'embedding_185',
 'embedding_186',
 'embedding_187',
 'embedding_188',
 'embedding_189',
 'embedding_190',
 'embedding_191',
 'embedding_192',
 'embedding_193',
 'embedding_194',
 'embedding_195',
 'embedding_196',
 'embedding_197',
 'embedding_198',
 'embedding_199',
 'embedding_200',
 'embedding_201',
 'embedding_202',
 'embedding_203',
 'embedding_204',
 'embedding_205',
 'embedding_206',
 'embedding_207',
 'embedding_208',
 'embedding_209',
 'embedding_210',
 'embedding_211',
 'embedding_212',
 'embedding_213',
 'embedding_214',
 'embedding_215',
 'embedding_216',
 'embedding_217',
 'embedding_218',
 'embedding_219',
 'embedding_220',
 'embedding_221',
 'embedding_222',
 'embedding_223',
 'embedding_224',
 'embedding_225',
 'embedding_226',
 'embedding_227',
 'embedding_228',
 'embedding_229',
 'embedding_230',
 'embedding_231',
 'embedding_232',
 'embedding_233',
 'embedding_234',
 'embedding_235',
 'embedding_236',
 'embedding_237',
 'embedding_238',
 'embedding_239',
 'embedding_240',
 'embedding_241',
 'embedding_242',
 'embedding_243',
 'embedding_244',
 'embedding_245',
 'embedding_246',
 'embedding_247',
 'embedding_248',
 'embedding_249',
 'embedding_250',
 'embedding_251',
 'embedding_252',
 'embedding_253',
 'embedding_254',
 'embedding_255',
 'embedding_256',
 'embedding_257',
 'embedding_258',
 'embedding_259',
 'embedding_260',
 'embedding_261',
 'embedding_262',
 'embedding_263',
 'embedding_264',
 'embedding_265',
 'embedding_266',
 'embedding_267',
 'embedding_268',
 'embedding_269',
 'embedding_270',
 'embedding_271',
 'embedding_272',
 'embedding_273',
 'embedding_274',
 'embedding_275',
 'embedding_276',
 'embedding_277',
 'embedding_278',
 'embedding_279',
 'embedding_280',
 'embedding_281',
 'embedding_282',
 'embedding_283',
 'embedding_284',
 'embedding_285',
 'embedding_286',
 'embedding_287',
 'embedding_288',
 'embedding_289',
 'embedding_290',
 'embedding_291',
 'embedding_292',
 'embedding_293',
 'embedding_294',
 'embedding_295',
 'embedding_296',
 'embedding_297',
 'embedding_298',
 'embedding_299',
 'embedding_300',
 'embedding_301',
 'embedding_302',
 'embedding_303',
 'embedding_304',
 'embedding_305',
 'embedding_306',
 'embedding_307',
 'embedding_308',
 'embedding_309',
 'embedding_310',
 'embedding_311',
 'embedding_312',
 'embedding_313',
 'embedding_314',
 'embedding_315',
 'embedding_316',
 'embedding_317',
 'embedding_318',
 'embedding_319',
 'embedding_320',
 'embedding_321',
 'embedding_322',
 'embedding_323',
 'embedding_324',
 'embedding_325',
 'embedding_326',
 'embedding_327',
 'embedding_328',
 'embedding_329',
 'embedding_330',
 'embedding_331',
 'embedding_332',
 'embedding_333',
 'embedding_334',
 'embedding_335',
 'embedding_336',
 'embedding_337',
 'embedding_338',
 'embedding_339',
 'embedding_340',
 'embedding_341',
 'embedding_342',
 'embedding_343',
 'embedding_344',
 'embedding_345',
 'embedding_346',
 'embedding_347',
 'embedding_348',
 'embedding_349',
 'embedding_350',
 'embedding_351',
 'embedding_352',
 'embedding_353',
 'embedding_354',
 'embedding_355',
 'embedding_356',
 'embedding_357',
 'embedding_358',
 'embedding_359',
 'embedding_360',
 'embedding_361',
 'embedding_362',
 'embedding_363',
 'embedding_364',
 'embedding_365',
 'embedding_366',
 'embedding_367',
 'embedding_368',
 'embedding_369',
 'embedding_370',
 'embedding_371',
 'embedding_372',
 'embedding_373',
 'embedding_374',
 'embedding_375',
 'embedding_376',
 'embedding_377',
 'embedding_378',
 'embedding_379',
 'embedding_380',
 'embedding_381',
 'embedding_382',
 'embedding_383',
 'embedding_384',
 'embedding_385',
 'embedding_386',
 'embedding_387',
 'embedding_388',
 'embedding_389',
 'embedding_390',
 'embedding_391',
 'embedding_392',
 'embedding_393',
 'embedding_394',
 'embedding_395',
 'embedding_396',
 'embedding_397',
 'embedding_398',
 'embedding_399',
 'embedding_400',
 'embedding_401',
 'embedding_402',
 'embedding_403',
 'embedding_404',
 'embedding_405',
 'embedding_406',
 'embedding_407',
 'embedding_408',
 'embedding_409',
 'embedding_410',
 'embedding_411',
 'embedding_412',
 'embedding_413',
 'embedding_414',
 'embedding_415',
 'embedding_416',
 'embedding_417',
 'embedding_418',
 'embedding_419',
 'embedding_420',
 'embedding_421',
 'embedding_422',
 'embedding_423',
 'embedding_424',
 'embedding_425',
 'embedding_426',
 'embedding_427',
 'embedding_428',
 'embedding_429',
 'embedding_430',
 'embedding_431',
 'embedding_432',
 'embedding_433',
 'embedding_434',
 'embedding_435',
 'embedding_436',
 'embedding_437',
 'embedding_438',
 'embedding_439',
 'embedding_440',
 'embedding_441',
 'embedding_442',
 'embedding_443',
 'embedding_444',
 'embedding_445',
 'embedding_446',
 'embedding_447',
 'embedding_448',
 'embedding_449',
 'embedding_450',
 'embedding_451',
 'embedding_452',
 'embedding_453',
 'embedding_454',
 'embedding_455',
 'embedding_456',
 'embedding_457',
 'embedding_458',
 'embedding_459',
 'embedding_460',
 'embedding_461',
 'embedding_462',
 'embedding_463',
 'embedding_464',
 'embedding_465',
 'embedding_466',
 'embedding_467',
 'embedding_468',
 'embedding_469',
 'embedding_470',
 'embedding_471',
 'embedding_472',
 'embedding_473',
 'embedding_474',
 'embedding_475',
 'embedding_476',
 'embedding_477',
 'embedding_478',
 'embedding_479',
 'embedding_480',
 'embedding_481',
 'embedding_482',
 'embedding_483',
 'embedding_484',
 'embedding_485',
 'embedding_486',
 'embedding_487',
 'embedding_488',
 'embedding_489',
 'embedding_490',
 'embedding_491',
 'embedding_492',
 'embedding_493',
 'embedding_494',
 'embedding_495',
 'embedding_496',
 'embedding_497',
 'embedding_498',
 'embedding_499',
 'embedding_500',
 'embedding_501',
 'embedding_502',
 'embedding_503',
 'embedding_504',
 'embedding_505',
 'embedding_506',
 'embedding_507',
 'embedding_508',
 'embedding_509',
 'embedding_510',
 'embedding_511']

In [10]:
embedding_df = spark.createDataFrame(embedding_vectors, schema=features_column_names)
embedding_df.show()

+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+

Add unique `row_id` to each row in the pysaprk dataframe

In [11]:
embedding_df= embedding_df.repartition(1).withColumn("id", F.monotonically_increasing_id())
embedding_df.show(2)

+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+-------------------+--------------------+--------------------+--------------------+-------------------+--------------------+-------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+-------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+---+

Add unique `row_id` to each row in our main pyspark dataframe `df`

In [12]:
df = df.repartition(1).withColumn("id", F.monotonically_increasing_id())
df.show(2)

+----------+--------------------+--------------------+--------------------+---+
|product_id|               title|         description|       combined_text| id|
+----------+--------------------+--------------------+--------------------+---+
|        P0|Men's 3X Large Ca...|This heavyweight,...|Men's 3X Large Ca...|  0|
|        P1|Turmode 30 ft. RP...|If you need more ...|Turmode 30 ft. RP...|  1|
+----------+--------------------+--------------------+--------------------+---+
only showing top 2 rows

In [13]:
df.show()

+----------+--------------------+--------------------+--------------------+---+
|product_id|               title|         description|       combined_text| id|
+----------+--------------------+--------------------+--------------------+---+
|        P0|Men's 3X Large Ca...|This heavyweight,...|Men's 3X Large Ca...|  0|
|        P1|Turmode 30 ft. RP...|If you need more ...|Turmode 30 ft. RP...|  1|
|        P2|Large Tapestry Bo...|Polyester cover r...|Large Tapestry Bo...|  2|
|        P3|16-Gauge-Sinks Ve...|It features a rec...|16-Gauge-Sinks Ve...|  3|
|        P4|Men's Crazy Horse...|This 9 in. black ...|Men's Crazy Horse...|  4|
|        P5|Mariana 6 ft. Mul...|With robust struc...|Mariana 6 ft. Mul...|  5|
|        P6|5 gal. #650C-2 Po...|BEHR PRO i300 Sem...|5 gal. #650C-2 Po...|  6|
|        P7|7/8 in. x 4-1/2 i...|DEWALT High Perfo...|7/8 in. x 4-1/2 i...|  7|
|        P8|  Ring Gold Bar Cart|This Ring Bar Car...|Ring Gold Bar Car...|  8|
|        P9|Traditional Silve...|This transitional...|Traditional Silve...|  9|
|       P10|15 in. x 59 in. O...|Its easy to add a...|15 in. x 59 in. O...| 10|
|       P11|1 qt. #350F-7 Wil...|BEHR PREMIUM PLUS...|1 qt. #350F-7 Wil...| 11|
|       P12|Anthracite Cordle...|BlindsAvenue ligh...|Anthracite Cordle...| 12|
|       P13|SlimGrip 78-Inch ...|Luverne SlimGrip ...|SlimGrip 78-Inch ...| 13|
|       P14|6 in. x 28 in. x ...|Our Rustic Collec...|6 in. x 28 in. x ...| 14|
|       P15|Espresso Cordless...|"The 2-1/2 in. Co...|Espresso Cordless...| 15|
|       P16|5 gal. #BL-W10 Ma...|BEHR PREMIUM PLUS...|5 gal. #BL-W10 Ma...| 16|
|       P17|Eleyn 26 in. Indo...|This lighted chro...|Eleyn 26 in. Indo...| 17|
|       P18|1 qt. #M400-5 Bab...|BEHR PREMIUM PLUS...|1 qt. #M400-5 Bab...| 18|
|       P19|10 in. x 4 in. x ...|Our faux wood bea...|10 in. x 4 in. x ...| 19|
+----------+--------------------+--------------------+--------------------+---+
only showing top 20 rows

In [14]:
embedding_df.show()

+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+---+

Let's join the two dataframes

In [15]:
df = df.join(embedding_df, on="id", how="inner").drop("id")
df.show(2)

+----------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+-------------------+--------------------+--------------------+--------------------+-------------------+--------------------+-------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+-------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+

In [16]:
df.count()

2000

### Task 3 - Cluster products using K-means

Assemble the 512 Embedding Columns into a Single 'features' Column

- VectorAssembler is used to combine features that are going to be used in the machine learning model

In [17]:
assembler = VectorAssembler(
    inputCols=features_column_names,
    outputCol="features"
)
data = assembler.transform(df)
data = data.select("product_id", "title", "description", "features")
data.show(2)

+----------+--------------------+--------------------+--------------------+
|product_id|               title|         description|            features|
+----------+--------------------+--------------------+--------------------+
|        P0|Men's 3X Large Ca...|This heavyweight,...|[0.04266477003693...|
|        P1|Turmode 30 ft. RP...|If you need more ...|[0.04413316026329...|
+----------+--------------------+--------------------+--------------------+
only showing top 2 rows

Apply K-Means Clustering with 5 Clusters on the `features` Column

 - Kmeans is a unsupervised machine learning technique, used to cluster the data points based on features

In [18]:
kmeans = KMeans(k=5, featuresCol='features', predictionCol='cluster')
model = kmeans.fit(data)
clustered_data = model.transform(data)
clustered_data.show()

+----------+--------------------+--------------------+--------------------+-------+
|product_id|               title|         description|            features|cluster|
+----------+--------------------+--------------------+--------------------+-------+
|        P0|Men's 3X Large Ca...|This heavyweight,...|[0.04266477003693...|      4|
|        P1|Turmode 30 ft. RP...|If you need more ...|[0.04413316026329...|      4|
|        P2|Large Tapestry Bo...|Polyester cover r...|[0.04236160591244...|      2|
|        P3|16-Gauge-Sinks Ve...|It features a rec...|[-0.0497337169945...|      0|
|        P4|Men's Crazy Horse...|This 9 in. black ...|[0.02608588151633...|      4|
|        P5|Mariana 6 ft. Mul...|With robust struc...|[0.06058844178915...|      0|
|        P6|5 gal. #650C-2 Po...|BEHR PRO i300 Sem...|[0.00749773625284...|      3|
|        P7|7/8 in. x 4-1/2 i...|DEWALT High Perfo...|[-0.0217796657234...|      4|
|        P8|  Ring Gold Bar Cart|This Ring Bar Car...|[-4.6415856922976...|      0|
|        P9|Traditional Silve...|This transitional...|[0.03908809646964...|      0|
|       P10|15 in. x 59 in. O...|Its easy to add a...|[6.00928789936006...|      1|
|       P11|1 qt. #350F-7 Wil...|BEHR PREMIUM PLUS...|[0.00136178603861...|      3|
|       P12|Anthracite Cordle...|BlindsAvenue ligh...|[-0.0231370851397...|      1|
|       P13|SlimGrip 78-Inch ...|Luverne SlimGrip ...|[0.02256619744002...|      4|
|       P14|6 in. x 28 in. x ...|Our Rustic Collec...|[0.01872418820858...|      1|
|       P15|Espresso Cordless...|"The 2-1/2 in. Co...|[-0.0370010994374...|      1|
|       P16|5 gal. #BL-W10 Ma...|BEHR PREMIUM PLUS...|[-0.0057130982168...|      3|
|       P17|Eleyn 26 in. Indo...|This lighted chro...|[-0.0420588180422...|      0|
|       P18|1 qt. #M400-5 Bab...|BEHR PREMIUM PLUS...|[0.00746711296960...|      3|
|       P19|10 in. x 4 in. x ...|Our faux wood bea...|[-0.0081119453534...|      1|
+----------+--------------------+--------------------+--------------------+-------+
only showing top 20 rows

### Task 4 - Visualize the clusters

Let's reduce the dimensionality of our features for visualization purpose

`512 dimensions => 2 dimensions`

- Use PCA to reduce dimensions and visualize product clusters interactively, highlighting relationships among items
- Used PySpark ML module called PCA: Principal Component Analysis
- PCA is a dimensionality reduction technique that fines the most important components of the data, making it possible to represent high dimensional data in a lower dimensional space while retaining as much information possible.

In [19]:
pca = PCA(k=2, inputCol='features', outputCol='pca_features')
pca_model = pca.fit(clustered_data)
pca_results = pca_model.transform(clustered_data)
pca_results.show()

+----------+--------------------+--------------------+--------------------+-------+--------------------+
|product_id|               title|         description|            features|cluster|        pca_features|
+----------+--------------------+--------------------+--------------------+-------+--------------------+
|        P0|Men's 3X Large Ca...|This heavyweight,...|[0.04266477003693...|      4|[0.18866841307422...|
|        P1|Turmode 30 ft. RP...|If you need more ...|[0.04413316026329...|      4|[-0.1739518653657...|
|        P2|Large Tapestry Bo...|Polyester cover r...|[0.04236160591244...|      2|[-0.0202219742633...|
|        P3|16-Gauge-Sinks Ve...|It features a rec...|[-0.0497337169945...|      0|[0.00737017697771...|
|        P4|Men's Crazy Horse...|This 9 in. black ...|[0.02608588151633...|      4|[-0.0240411743756...|
|        P5|Mariana 6 ft. Mul...|With robust struc...|[0.06058844178915...|      0|[-0.0015003784667...|
|        P6|5 gal. #650C-2 Po...|BEHR PRO i300 Sem...|[0.00749773625284...|      3|[0.66973343978943...|
|        P7|7/8 in. x 4-1/2 i...|DEWALT High Perfo...|[-0.0217796657234...|      4|[0.07967861605320...|
|        P8|  Ring Gold Bar Cart|This Ring Bar Car...|[-4.6415856922976...|      0|[-0.1047407594599...|
|        P9|Traditional Silve...|This transitional...|[0.03908809646964...|      0|[-0.1110959655302...|
|       P10|15 in. x 59 in. O...|Its easy to add a...|[6.00928789936006...|      1|[0.17252524140482...|
|       P11|1 qt. #350F-7 Wil...|BEHR PREMIUM PLUS...|[0.00136178603861...|      3|[0.69691602016073...|
|       P12|Anthracite Cordle...|BlindsAvenue ligh...|[-0.0231370851397...|      1|[-0.0897581612040...|
|       P13|SlimGrip 78-Inch ...|Luverne SlimGrip ...|[0.02256619744002...|      4|[2.95610256824078...|
|       P14|6 in. x 28 in. x ...|Our Rustic Collec...|[0.01872418820858...|      1|[0.02673300154363...|
|       P15|Espresso Cordless...|"The 2-1/2 in. Co...|[-0.0370010994374...|      1|[0.02586194090687...|
|       P16|5 gal. #BL-W10 Ma...|BEHR PREMIUM PLUS...|[-0.0057130982168...|      3|[0.66953163724613...|
|       P17|Eleyn 26 in. Indo...|This lighted chro...|[-0.0420588180422...|      0|[0.00503157006498...|
|       P18|1 qt. #M400-5 Bab...|BEHR PREMIUM PLUS...|[0.00746711296960...|      3|[0.68253568889748...|
|       P19|10 in. x 4 in. x ...|Our faux wood bea...|[-0.0081119453534...|      1|[0.11025094595553...|
+----------+--------------------+--------------------+--------------------+-------+--------------------+
only showing top 20 rows

- pca_features is a vector with two-dimensions now
- features col has 512 dimensions

Convert to pandas dataframe

In [20]:
pca_df = pca_results.select("product_id", "pca_features", "cluster").toPandas()
pca_df

     product_id                                  pca_features  cluster
0            P0     [0.1886684130742236, 0.03427901044484978]        4
1            P1   [-0.1739518653657075, -0.13301099780082298]        4
2            P2     [-0.02022197426334011, 0.316323140200805]        2
3            P3  [0.007370176977716268, 0.059317857231531976]        0
4            P4  [-0.02404117437560953, -0.04419558569164092]        4
...         ...                                           ...      ...
1995      P1995    [0.15093757018981876, 0.29625568679412906]        0
1996      P1996    [-0.05670165084806678, 0.5847982511312442]        2
1997      P1997   [0.1078274397804236, -0.004749321763927287]        1
1998      P1998      [0.6915221979314057, 0.0969951268387874]        3
1999      P1999    [-0.08231135941123359, 0.5317282822422784]        2

[2000 rows x 3 columns]

In [21]:
pca_df[['x', 'y']] = pd.DataFrame(pca_df['pca_features'].tolist(), index=pca_df.index)

In [22]:
pca_df

,product_id,pca_features,cluster,x,y
0,P0,"[0.1886684130742236, 0.03427901044484978]",4,0.188668,0.034279
1,P1,"[-0.1739518653657075, -0.13301099780082298]",4,-0.173952,-0.133011
2,P2,"[-0.02022197426334011, 0.316323140200805]",2,-0.020222,0.316323
3,P3,"[0.007370176977716268, 0.059317857231531976]",0,0.007370,0.059318
4,P4,"[-0.02404117437560953, -0.04419558569164092]",4,-0.024041,-0.044196
...,...,...,...,...,...
1995,P1995,"[0.15093757018981876, 0.29625568679412906]",0,0.150938,0.296256
1996,P1996,"[-0.05670165084806678, 0.5847982511312442]",2,-0.056702,0.584798
1997,P1997,"[0.1078274397804236, -0.004749321763927287]",1,0.107827,-0.004749
1998,P1998,"[0.6915221979314057, 0.0969951268387874]",3,0.691522,0.096995
1999,P1999,"[-0.08231135941123359, 0.5317282822422784]",2,-0.082311,0.531728

Let's plot the Clusters

In [23]:
def plot_clusters(pca_df, num_clusters=5):
    """
    Plots a 2D visualization of clusters using Plotly Express.

    Parameters:
    - pca_df (DataFrame): A Pandas DataFrame containing columns 'x', 'y', and 'cluster'.
      'x' and 'y' are the 2D PCA components, and 'cluster' indicates the cluster label.
    - num_clusters (int): The number of unique clusters to display.
    - recently_viewed_df (DataFrame, optional): DataFrame with 'x' and 'y' coordinates for recently viewed products.

    This function creates an interactive scatter plot where each point is colored according to its cluster.
    Recently viewed products are marked as black crosses if provided.

    Returns:
    - fig (Figure): The Plotly figure object for the plot.
    """

    # Create the base cluster plot
    fig = px.scatter(
        pca_df,
        x='x',
        y='y',
        opacity=0.6,
        size_max=4,
        color= pca_df.cluster.astype(str),
        title='2D Visualization of Clusters with Recently Viewed Products',
        labels={'x': 'PCA Component 1', 'y': 'PCA Component 2'},
        category_orders={'cluster': list(range(num_clusters))},
        # show the product id in the tooltip
        hover_data={'product_id': True}

    )

    # Update layout to add legend title and adjust plot settings
    fig.update_layout(legend_title_text='Clusters', legend=dict(x=1, y=1), width=600, height=500)

    return fig

fig = plot_clusters(pca_df)
fig.show()

### Task 5 - Highlight recently viewed products

List of 8 products recently viewed by the user.

In [24]:
recently_viewed_products = [
    'P316',
    'P333',
    'P1115',
    'P1691',
    'P1082',
    'P397',
    'P1441',
    'P1054',
]

In [25]:
print("The user has recently viewed the following products: ", recently_viewed_products)

The user has recently viewed the following products:  ['P316', 'P333', 'P1115', 'P1691', 'P1082', 'P397', 'P1441', 'P1054']

Let's have a look at the records in our `clustered_data` dataframe related to the recently viewed products.

In [26]:
clustered_data.show()

+----------+--------------------+--------------------+--------------------+-------+
|product_id|               title|         description|            features|cluster|
+----------+--------------------+--------------------+--------------------+-------+
|        P0|Men's 3X Large Ca...|This heavyweight,...|[0.04266477003693...|      4|
|        P1|Turmode 30 ft. RP...|If you need more ...|[0.04413316026329...|      4|
|        P2|Large Tapestry Bo...|Polyester cover r...|[0.04236160591244...|      2|
|        P3|16-Gauge-Sinks Ve...|It features a rec...|[-0.0497337169945...|      0|
|        P4|Men's Crazy Horse...|This 9 in. black ...|[0.02608588151633...|      4|
|        P5|Mariana 6 ft. Mul...|With robust struc...|[0.06058844178915...|      0|
|        P6|5 gal. #650C-2 Po...|BEHR PRO i300 Sem...|[0.00749773625284...|      3|
|        P7|7/8 in. x 4-1/2 i...|DEWALT High Perfo...|[-0.0217796657234...|      4|
|        P8|  Ring Gold Bar Cart|This Ring Bar Car...|[-4.6415856922976...|      0|
|        P9|Traditional Silve...|This transitional...|[0.03908809646964...|      0|
|       P10|15 in. x 59 in. O...|Its easy to add a...|[6.00928789936006...|      1|
|       P11|1 qt. #350F-7 Wil...|BEHR PREMIUM PLUS...|[0.00136178603861...|      3|
|       P12|Anthracite Cordle...|BlindsAvenue ligh...|[-0.0231370851397...|      1|
|       P13|SlimGrip 78-Inch ...|Luverne SlimGrip ...|[0.02256619744002...|      4|
|       P14|6 in. x 28 in. x ...|Our Rustic Collec...|[0.01872418820858...|      1|
|       P15|Espresso Cordless...|"The 2-1/2 in. Co...|[-0.0370010994374...|      1|
|       P16|5 gal. #BL-W10 Ma...|BEHR PREMIUM PLUS...|[-0.0057130982168...|      3|
|       P17|Eleyn 26 in. Indo...|This lighted chro...|[-0.0420588180422...|      0|
|       P18|1 qt. #M400-5 Bab...|BEHR PREMIUM PLUS...|[0.00746711296960...|      3|
|       P19|10 in. x 4 in. x ...|Our faux wood bea...|[-0.0081119453534...|      1|
+----------+--------------------+--------------------+--------------------+-------+
only showing top 20 rows

In [27]:
filtered_data = clustered_data.where(F.col("product_id").isin(recently_viewed_products))
filtered_data.show()

+----------+--------------------+--------------------+--------------------+-------+
|product_id|               title|         description|            features|cluster|
+----------+--------------------+--------------------+--------------------+-------+
|      P316|Mystic Fitz Roy B...|With its distress...|[-0.0157568920403...|      2|
|      P333|Florida Shag Beig...|Lavish natural mo...|[-0.0112434905022...|      2|
|      P397|1 gal. #M250-3 Ap...|BEHR ULTRA SCUFF ...|[-0.0059162145480...|      3|
|     P1054|1 gal. #HDPG60 Mi...|The improved PPG ...|[-0.0048829163424...|      3|
|     P1082|1 qt. #S220-7 Mol...|BEHR ULTRA SCUFF ...|[-0.0216461066156...|      3|
|     P1115|Modern Gray/Multi...|This Modern Gray/...|[-0.0226364415138...|      2|
|     P1441|1 qt. #PPU6-06 Ho...|BEHR PREMIUM PLUS...|[-0.0062980493530...|      3|
|     P1691|Genet Rust/Red-Br...|Add a refreshing ...|[-0.0304906144738...|      2|
+----------+--------------------+--------------------+--------------------+-------+

In [28]:
unique_clusters = filtered_data.select("cluster").distinct().rdd.flatMap(lambda x: x).collect()
print("Unique clusters from recently viewed products: ", unique_clusters)

Unique clusters from recently viewed products:  [2, 3]

### Task 6 - Recommend products based on recently viewed products

Let's have a look at the recently viewed products titles

In [29]:
filtered_data.select("title").rdd.flatMap(lambda x: x).collect()

# User was looking for rugs and interior paint & primer
# Use product recommender system to suggest similar products

["Mystic Fitz Roy Beige 9' 0 x 12' 0 Area Rug",
 'Florida Shag Beige/Multi 3 ft. x 5 ft. Floral Area Rug',
 '1 gal. #M250-3 Apple Turnover Extra Durable Flat Interior Paint & Primer',
 '1 gal. #HDPG60 Misty Emerald Lake Flat Interior Paint and Primer',
 '1 qt. #S220-7 Molasses Extra Durable Flat Interior Paint & Primer',
 'Modern Gray/Multi 9 ft. x 12 ft. Vibrant Abstract Polyester Area Rug',
 '1 qt. #PPU6-06 Honey Locust Eggshell Enamel Low Odor Interior Paint & Primer',
 'Genet Rust/Red-Brown 8 ft. x 11 ft. Abstract Wool Area Rug']

Let's see the distinct clusters of the recenetly viewed products.

In [30]:
print(unique_clusters)

[2, 3]

Let's find the possible products for the recommendation.

In [31]:
# filter only products in similar cluster
# exclude recently viewed products from recommendations

possible_recommendations = clustered_data.filter(clustered_data['cluster'].isin(unique_clusters)).filter(~clustered_data['product_id'].isin(recently_viewed_products))

Let's perform a groupby and generate a list of product IDs that can be recommended for each of the clusters.

In [32]:
recommendations = possible_recommendations.groupby("cluster").agg(F.collect_list("product_id").alias("recommendations"))
recommendations_df = recommendations.toPandas()
recommendations_df['random_recommendations'] = recommendations_df['recommendations'].apply(lambda x: np.random.choice(x, size=5, replace=False).tolist())

In [33]:
recommendations_df.head()

,cluster,recommendations,random_recommendations
0,2,"[P2, P21, P52, P71, P87, P101, P108, P119, P12...","[P538, P1318, P1721, P149, P1991]"
1,3,"[P6, P11, P16, P18, P24, P26, P30, P33, P40, P...","[P359, P692, P1968, P1276, P1750]"

In [ ]:
# write a python function to display the recommendations
def display_recommendations(row):
  # find the title of the product in df
  product_ids = row['random_recommendations']
  cluster = row.cluster

  titles = data. \
          filter(data["product_id"]. \
          isin(product_ids)).select("title").collect()

  print("\n")
  print("Recommendations for Cluster:", cluster)
  for title in titles:
    print(title[0])

recommendations_df.apply(display_recommendations, axis=1)

Recommendations for Cluster: 2
Old Farm Driftwood 8 ft. x 10 ft. Tweed Indoor/Outdoor Oval Area Rug
Lyndhurst Multi/Green 10 ft. x 14 ft. Border Area Rug
Montauk Beige/Ivory 4 ft. x 4 ft. Striped Distressed Geometric Round Area Rug
NFL - Las Vegas Raiders Black Man Cave 3 ft. x 4 ft. Area Rug
Adirondack Ivory/Silver 6 ft. x 6 ft. Square Geometric Border Area Rug


Recommendations for Cluster: 3
5 gal. #PPG1091-6 Tan Your Hide Semi-Gloss Interior Paint and Primer
1 gal. #500E-2 Aqua Breeze Eggshell Enamel Interior Stain-Blocking Paint & Primer
1 gal. #MQ5-33 Uptown Girl One-Coat Hide Semi-Gloss Enamel Interior Stain-Blocking Paint & Primer
5 gal. #760C-2 Country Beige Eggshell Interior Paint
5 gal. #HDGG31U Mountain Mist Satin Interior Paint with Primer

0    None
1    None
dtype: object

----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 58727)
Traceback (most recent call last):
  File "C:\Users\ashle\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\ashle\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\ashle\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\ashle\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 755, in __init__
    self.handle()
  File "c:\Users\ashle\Project\usecase\venv\Lib\site-packages\pyspark\accumulators.py", line 303, in handle
    poll(accum_updates)
  File "c:\Users\ashle\Project\usecase\venv\Lib\site-packages\pyspark\accumulators.py", line 272, in poll
    if self.rfile in r and func():
                           ^^^^^^
  File "c:\Users\ashle\Project\usecase\venv\Lib\site-packages\pyspark\accumulators.py", line 276, in accum_updates
    num_updates = read_int(self.rfile)
                  ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ashle\Project\usecase\venv\Lib\site-packages\pyspark\serializers.py", line 595, in read_int
    length = stream.read(4)
             ^^^^^^^^^^^^^^
  File "C:\Users\ashle\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------